version: 2

jobs:
  wpcs:
      docker:
        - image: notnoopci/php:7.0-apache-node
      steps:
        - checkout
        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run:
            name: Install WPCS
            command: |
              sudo composer self-update
              composer global require hirak/prestissimo
              composer install
        - save_cache:
            paths:
              - ./vendor
            key: v1-dependencies-{{ checksum "composer.json" }}
        - run:
            name: Run WPCS
            command: vendor/bin/phpcs

workflows:
  version: 2
  test_and_standards:
    jobs:
      - wpcs:
          filters:
            branches:
              ignore: develop